name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Se ejecutará cada vez que hagas un push a la rama main

# Permisos necesarios para interactuar con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita que múltiples despliegues simultáneos se pisen entre sí
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Cachea las dependencias para que el deploy sea ultra rápido

      - name: Instalar dependencias
        run: npm ci # Instalación limpia basada estrictamente en tu package-lock.json

      - name: Construir aplicación (Build)
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Sube la carpeta 'dist' que genera Vite

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
