name: Deploy Landing Page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto (Build)
        run: npm run build

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
